### PR TITLE
Feat: useServerSentEvents

### PR DESCRIPTION
**Pull request by rliang**
* Provides a solution for real-time data streaming
* Based on `ReadableStream`, which is compatible with Hattip responses
* Using `@microsoft/fetch-event-source` rather than vanilla `EventSource` for increased flexibility, e.g. the ability to obtain response headers

### CODE REVIEW

**Comment by cyco130** [comment]
Oh, this is cool!

Hot reloading tests fail because of deps optimization problems. Easily fixed by adding `@microsoft/fetch-event-source` to `optimizeDeps.include`.

I'll have a look at the other failing tests to understand what's going on.

**Comment by rliang** [comment]
Thanks! By `optimizeDeps.include`, do you mean the one at `src/vite-plugin/inject-config.ts`?

**Comment by cyco130** [comment]
Yes, exactly.

**Comment by rliang** [comment]
Great, looks like that did the trick.

**Comment by cyco130** [comment]
I tried it and gave it quite a bit of thought.

This is a great API for a live data view: think of a live `Avatar` component that updates itself every time the user updates their profile photo. It can be immensely useful in some circumstances. But for the general case, it may direct Rakkas users to bad practices: One TCP connection per live view is very expensive, especially if you consider only **six concurrent open SSE connections per browser** are allowed at any one time. So having multiple `useSSE` calls in an app should be highly discouraged. Even a single call within a component that's instantiated multiple times can cause problems. 

I don't have a fully clear picture in my head yet but I feel like we can come up with a solution that requires one live connection per open tab and do the multiplexing ourselves on the client.

A second consideration is the API itself: This is API great for a live view. But an event-based API (`useSSE(() => { ... }, { onMessage(message) { ... })`) would be more useful for things like notifications.

I want to give this a bit more thought before committing to a solution. This is a good solution but I don't want to miss a great one and I feel a great one is hiding somewhere in there :)

Feel free to ping me on Discord, we can develop the idea together.

**Comment by rliang** [comment]
> One TCP connection per live view is very expensive, especially if you consider only **six concurrent open SSE connections per browser** are allowed at any one time. So having multiple `useSSE` calls in an app should be highly discouraged. Even a single call within a component that's instantiated multiple times can cause problems.

Good point, hadn't considered it.

> I don't have a fully clear picture in my head yet but I feel like we can come up with a solution that requires one live connection per open tab and do the multiplexing ourselves on the client.

Multiplexing on the client seems relatively straightforward to implement, probably would only need to wrap the app with a context provider holding the request. Though on the server, I think it will require quite a bit of book-keeping. I'll also think about a design if I get more spare time.

> A second consideration is the API itself: This is API great for a live view. But an event-based API (`useSSE(() => { ... }, { onMessage(message) { ... })`) would be more useful for things like notifications.

Agreed. Though I initially wrote it like this since what you described can also be achieved with `useEffect(() => { ... }, [message])`.

**Comment by cyco130** [comment]
Yeah, I couldn't wrap my head around how to implement the server-side multiplexing.

I did some research and turns out HTTP/2 improves things a lot, the limit is more like about a hundred connections. But the connection limit is still a concern on development time.

It's useful as is, I'll merge it today but remove its docs from the table of contents for now. I'd like to think about documented features as final, or at least close to final. We can document it once we're more confident on the API.

**Comment by rliang** [comment]
Sounds good!

**Comment by cyco130** [comment]
Published in 0.6.17!

**Comment by cyco130** [comment]
Hi @rliang,

I'm writing here because I don't have any other contact info. I invited you to Rakkas org on GitHub. Don't think of it as a responsibility, you aren't expected to do anything. Thank you for your contributions so far, and, if you accept, welcome aboard!

If you use Discord, please add me there too! fatih#2408

**Pull request merged**
